server:
  port: 8080

spring:
  application:
    name: fashoj-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
        - id: problem-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/problems/**
        - id: submission-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/submissions/**
        - id: judge-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/judge/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always