server:
  port: 8082

spring:
  application:
    name: fashoj-problem-service
  datasource:
    url: jdbc:mysql://localhost:3306/fashoj?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: fashoj
    password: fashoj123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

# MinIO配置
minio:
  endpoint: http://localhost:9000
  access-key: fashoj
  secret-key: fashoj123
  bucket-name: fashoj-problems

# SpringDoc配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  info:
    title: FashOJ Problem Service API
    description: 题目服务API文档
    version: 1.0.0

logging:
  level:
    com.fashoj: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always